name: Deploy Lambda Get Weather Info

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.1.x']

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    - name: Install dotNet AWS Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools
    - name: lista local
      run: ls
    - name: Install dependencies
      run: dotnet restore fn-get-weather-info/src/fn-get-weather-info
    - name: Build
      run: dotnet build --configuration Release --no-restore fn-get-weather-info/src/fn-get-weather-info
    - name: Test
      run: dotnet test --no-restore --verbosity normal fn-get-weather-info/src/fn-get-weather-info
    - name: Deploy AWS
      run: dotnet lambda deploy-function fn-get-weather-info --aws-access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --aws-secret-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}  -pl fn-get-weather-info/src/fn-get-weather-info